working_directory="/Users/radwo/workspace"

import = [
    "~/.config/alacritty/themes/themes/deep_space.toml"
]

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]

[window]
padding.x = 2
padding.y = 2
opacity = 1.0
startup_mode = "Fullscreen"

[font]
normal.family = "RobotoMono Nerd Font Mono"
normal.style = "Regular"
bold.family = "RobotoMono Nerd Font Mono"
bold.style = "Bold"
italic.family = "RobotoMono Nerd Font Mono"
italic.style = "Italic"
bold_italic.family = "RobotoMono Nerd Font Mono"
bold_italic.style = "Bold Italic"
size = 10.0
